---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: index.md
  label: Home
  match: "**/*"
- type: document
  path: bakery.md
  label: bakery
  match: "**/*"
- type: document
  path: catering.md
  label: catering
  match: "**/*"
- type: document
  path: kaffebar.md
  label: kaffebar
  match: "**/*"
- type: document
  path: kontakt.md
  label: kontakt
  match: "**/*"
- type: document
  path: impressum.md
  label: impressum
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
