---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: index.md
  label: home
- type: directory
  path: news
  label: home news
  create: documents
  match: "**/*"
- type: document
  path: kaffebar.md
  label: kaffe
- type: directory
  path: bohnen
  label: neue bohnen
  create: documents
  match: "**/*"
  templates:
  - bohnen-post
- type: document
  path: bakery.md
  label: bakery
- type: document
  path: catering.md
  label: catering
- type: directory
  path: produkte
  label: catering produkte
  create: documents
  match: "**/*"
  templates:
  - produkte-post
- type: document
  path: kontakt.md
  label: kontakt
- type: document
  path: impressum.md
  label: impressum
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site/
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
