---
label: produkte
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
  hidden: true
  default: post.liquid
- type: text
  name: tags
  label: tags
  hidden: true
  default: bohne
- type: datetime
  name: date
  label: date
- name: image
  type: file
  config:
    maxSize: 64
  label: image
pages:
- bohnen/super-nice-bohne.md
